[providers]
providers = ["python", "node"]

[setup]
aptPkgs = ["ffmpeg", "libopus-dev", "build-essential"]

[install]
cmds = [
    "python -m pip install --upgrade pip", 
    "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
